language: ruby
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS circles_test CHARACTER SET utf8mb4;'
- cp ./.travis.database.yml ./config/database.yml
after_success:
- openssl aes-256-cbc -k $DEPLOY_KEY -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa
- ls -l config
- cat config/deploy_id_rsa
- bundle exec cap production deploy
env:
  global:
    secure: Qm/fZ1aibA+V+FVJtqRVAPqqvAV/l3tsfVcTE7w19SwOuSDwRDTFciKEEdf8BO5eoh8wPu/mzB634GF3Q1+3C8IYBoD7+MhI+9X6CD0hummckaHyO5qls70+QlwRAvDhQUOe1TvvsNR8hXgJDsRwAaehs89/qGSG7+dyFRFHc7txzFnJcctyjHUkkSNco1nsUzYh2auqNLRGcuIqYkYVXg+/eiTWbUzJCOsMPvtadFAv94Et8VGhPRTnruBl+M619EF/+4iTi59P8kWrp8hyl7UEyqgbRrvlvBgrk1XPtGQAPtH/QCLFUsIcQxod84TPSTe6HQV36vHSLTamHmWJ1jCe5rrK62TL0yvqPlLx7T8Xn+RrKr3ZUXZtq+MiX2QArZYRGDkrd+oHMfz4UTTr/kV9OkUDNgZQTqZTVWtooMcYqDMa6xlRC5ZLg0AnqDZYKo0DEs+QcD4N+N0qulSXl+PRE0mc8C4M08ETvmz2qe6Z93kQtLuJeyezWwQa7qfxnJrtQfAbW03/+l2y1/HY7qXlRQ5HCnKxkjLB2vD6xmP6CC6kH1K0WPGAdEhdzFqxGXE9pV/s4Ev6kxUegvrvgT8cWT4qVAoDNQfSmZftlx6tkx0UeaRKQsX0nBBta2B1Nz6fIwbb7OOgj2CFX2h0B+7SX76HHVgLdZjcC1dcHfU=
